### ISSUE TITLE
[Idea] Time-Lock Application using uPort Identities

### ISSUE THREAD

**Issue by KamesCG** [3box/sss-wasm#3]
@oed Continuing our conversation from Twitter (regarding sharing secrets via public ethereum keys), it might be interesting to associate uPort addresses with public/private encryption keys, so they could be used in an application using the Kimono protocol?

https://github.com/hillstreetlabs/kimono

Trusted digital identities can participate in time-lock protocol?

Thoughts?

**Comment by oed** [comment]
Closing this since it doesn't seem relevant.
