### ISSUE TITLE
[Idea] Add this binding to dsprenkels/sss README?

### ISSUE THREAD

**Issue by dsprenkels** [3box/sss-wasm#5]
Would you like me to add this repository to the [bindings list](https://github.com/dsprenkels/sss#bindings) in the `dsprenkels/sss` repo `README.md`?

**Comment by oed** [comment]
@dsprenkels yes, that would be great :D

**Comment by dsprenkels** [comment]
Awesome, I added it in https://github.com/dsprenkels/sss/pull/20.

**Comment by oed** [comment]
Great, thanks!
